src/recipe_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
#import login_view and logout_view from the views
from .views import login_view, logout_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('recipes.urls')),
    path('recipes/', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

#extend the urlpatterns parameter to include media information
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/recipes/urls.py
from django.urls import path
from .views import home
from .views import RecipeListView, RecipeDetailView, records

#specify the app name
app_name = 'recipes'

#URL configuration which maps a route with it's corresponding view
urlpatterns = [
   path('', home, name='home'),
   path('list/', RecipeListView.as_view(), name='list'),
   path('list/<pk>', RecipeDetailView.as_view(), name='detail'),
   path('records/', records, name='records'),
]

src/recipes/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.
class Recipe(models.Model):
    name=models.CharField(max_length=50)
    description = models.TextField(default='This recipe promises not to dissappoint')
    ingredients=models.CharField(max_length=255)
    cooking_time=models.PositiveIntegerField(help_text= 'in minutes')
    pic = models.ImageField(upload_to='recipes', default='no_picture.jpg')

    

    def __str__(self): 
        return (
            f"Recipe ID: {self.id}\n"
            f"Name: {self.name}\n"
            f"Ingredients: {self.ingredients}\n"
            f"Cooking Time: {self.cooking_time} minutes\n"

        )

    def calculate_difficulty(self):
        if self.cooking_time < 10 and len(self.ingredients.split(', ')) < 4:
            return 'Easy'
        elif self.cooking_time < 10 and len(self.ingredients.split(', ')) >= 4:
            return 'Medium'
        elif self.cooking_time >= 10 and len(self.ingredients.split(', ')) < 4:
            return 'Intermediate'
        elif self.cooking_time >= 10 and len(self.ingredients.split(', ')) >= 4:
            return 'Hard'

    def get_absolute_url(self):
       return reverse ('recipes:detail', kwargs={'pk': self.pk})

src/recipes/forms.py
from django import forms
from django.forms import TextInput, Select, ModelForm
from django.core.exceptions import ValidationError
#import gettext_lazy() as _() for future translation of site
from django.utils.translation import gettext_lazy as _

from .models import Recipe



CHART_CHOICES = (          #specify choices as a tuple
   ('#1', 'Bar chart'),    # when user selects "Bar chart", it is stored as "#1"
   ('#2', 'Pie chart'),
   ('#3', 'Line chart')
   )



class RecipeSearchForm(forms.Form):
    ingredient = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Search by Ingredient', 'class': 'ingredient-input input-box'}),
        
        max_length=100,
        required=False,
    )
    chart_type = forms.ChoiceField(widget=forms.Select(attrs={'class': 'chart-input input-box'}),choices=CHART_CHOICES, required=True)

    #override clean() method and validate recipe name data
    def clean_recipe_name(self):
        data = self.cleaned_data.get("recipe_name")

        if not data:
            raise forms.ValidationError(_('Please enter a valid recipe name'))
        return data

src/recipe_project/views.py
from django.shortcuts import render, redirect  
#Django authentication libraries           
from django.contrib.auth import authenticate, login
#Django Form for authentication
from django.contrib.auth.forms import AuthenticationForm   
#import the django login, logout package
from django.contrib.auth import authenticate, login, logout

#define a function view called login_view that takes a request from user
def login_view(request):
   #initialize:
   #error_message to None                                 
   error_message = None   
   #form object with username and password fields                             
   form = AuthenticationForm()                            


   #when user hits "login" button, then POST request is generated
   if request.method == 'POST':       
       #read the data sent by the form via POST request                   
       form =AuthenticationForm(data=request.POST)

       #check if form is valid
       if form.is_valid():                                
           username=form.cleaned_data.get('username')      #read username
           password = form.cleaned_data.get('password')    #read password

           #use Django authenticate function to validate the user
           user=authenticate(username=username, password=password)
           if user is not None:                    #if user is authenticated
          #then use pre-defined Django function to login
               login(request, user)                
               return redirect('recipes:list') #& send the user to desired page
       else:                                               #in case of error
           error_message ='ooops.. something went wrong'   #print error message

   #prepare data to send from view to template
   context ={                                             
       'form': form,                                 #send the form data
       'error_message': error_message                     #and the error_message
   }
   #load the login page using "context" information
   return render(request, 'auth/login.html', context)

#define a function view called logout_view that takes a request from user
def logout_view(request):                                  
   logout(request)             #the use pre-defined Django function to logout
   return render(request, 'auth/success.html')    #after logging out go to success page

src/recipes/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView   #to display lists and details
from .models import Recipe                #to access Recipe model
#to protect class-based view
from django.contrib.auth.mixins import LoginRequiredMixin
#to protect function-based views
from django.contrib.auth.decorators import login_required
from .forms import RecipeSearchForm
import pandas as pd
from .utils import get_chart
from django.db.models import Q

# Create your views here.
def home(request):
   return render(request, 'recipes/recipes_home.html')

#define function-based view - records()
#keep protected
#@login_required
def records(request):
   #create an instance of RecipeSearchForm defined in recipes/forms.py
   form = RecipeSearchForm(request.POST or None)
   recipes_df=None   #initialize dataframe to None
   chart = None    #initialize chart to None


   #check if the button is clicked
   if request.method =='POST':
      #read book_title and chart_type
      ingredient = request.POST.get('ingredient')
      chart_type = request.POST.get('chart_type')

      #apply filter to extract data
      qs =Recipe.objects.filter(Q(ingredients__icontains=ingredient))
      if qs:      #if data found
         #convert the queryset values to pandas dataframe
         recipes_df=pd.DataFrame(qs.values(), columns=['id', 'name', 'ingredients', 'cooking_time', 'description']) 
         #call get_chart by passing chart_type from user input, sales dataframe and labels
         chart=get_chart(chart_type, recipes_df)

         links = []

         for e, nam in enumerate(recipes_df['name']):
            nam = '<a href="/list/' + str(recipes_df['id'][e]) + '">' + str(nam) + '</a>'
            links.append(nam)

         recipes_df['name'] = links

         #convert the dataframe to HTML
         recipes_df=recipes_df.to_html(index=False, escape=False, classes='table table-success table-striped')

   #pack up data to be sent to template in the context dictionary
   context={
           'form': form,
           'recipes_df': recipes_df,
           'chart': chart
            }

   #load the recipes/record.html page using the data just prepared    
   return render(request, 'recipes/records.html', context)

# Create recipe class based view
class RecipeListView(LoginRequiredMixin, ListView):           #class-based “protected” view
   model = Recipe                         #specify model
   template_name = 'recipes/main.html'    #specify template 

class RecipeDetailView(LoginRequiredMixin, DetailView):                   #class-based “protected” view
   model = Recipe                                        #specify model
   template_name = 'recipes/detail.html'                 #specify template

src/recipes/templates/recipes/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="{% static 'recipes/css/style.css' %}" />
        <!--google icons reference location to get directory-->
        <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />
        <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />

        <title>Recipe</title>
        <style>
            .recipe-detail-container {
                width: 100%;
                height: 100vh;
                background-color: #dbe2e5;
            }

            .recipe-detail-banner {
                width: 100%;
                height: 50vh;
                background-image: linear-gradient(
                        rgba(149, 21, 10, 0.75),
                        rgba(149, 21, 10, 0.75)
                    ),
                    url(../../static/recipes/images/recipe_list_page_pic.jpg);
                background-size: cover;
                background-position: center;
            }

            .recipe-header-container {
                width: 60%;
                margin: auto;
                padding: 5% 0 2% 0;
            }

            .recipe-header-container h2 {
                margin-left: 5px;
                font-weight: 800;
                font-size: 3em;
                color: #fff;
            }

            .row {
                display: flex;
            }

            .recipe-detail-navbar {
                width: 85%;
                margin-bottom: 30px;
                padding: 35px 0 10px 0;
                display: flex;
                align-items: center;
                justify-content: space-between;
            }

            .recipe-detail-navbar ul li {
                list-style: none;
                display: inline-block;
                margin: 0 15px;
            }

            .recipe-detail-navbar ul li a {
                list-style: none;
                text-decoration: none;
                color: var(--color-white);
                transition: var(--transition);
            }

            .recipe-item-container {
                width: 60%;
                height: 300px;
                display: grid;
                grid-template-columns: repeat(2, 1fr);
                margin: 50px auto;
            }

            .recipe-item-pic img {
                object-fit: cover;
                width: 100%;
                height: 100%;
            }

            .recipe-item-details {
                background-color: #fff;
                background-size: cover;
            }

            .recipe-item-details {
                display: flex;
                flex-direction: column;
                gap: 3px;
            }

            .item-stats {
                text-transform: capitalize;
                border: 2px solid #d6d6d6;
                color: #000;
                border-radius: 2px;
                justify-content: flex-start;
                margin: 20px 0px 20px 20px;
                padding: 5px;
            }

            .bold {
                font-weight: 500;
            }

            .recipe-items {
                margin: 18px 20px;
            }

            hr {
                width: 80%;
                margin: 5px 20px;
            }
        </style>
    </head>
    <body>
        <div class="recipe-detail-container">
            <div class="recipe-detail-banner">
                <div class="recipe-header-container">
                    <div class="recipe-detail-navigation">
                        <nav class="recipe-detail-navbar">
                            <ul class="primary-links row">
                                <li>
                                    <a href="{% url 'recipes:home' %}">Home</a>
                                </li>
                                <li>
                                    <a href="{% url 'recipes:list' %}"
                                        >Recipes</a
                                    >
                                </li>
                                <li><a href="#">Create Recipe</a></li>
                                <li><a href="{% url 'recipes:records' %}">Search</a></li>
                                <li><a href ="{%url 'logout' %}">Logout</a></li>
                            </ul>
                        </nav>
                    </div>

                    <h2 class="recipe-name">{{object.name}}</h2>
                </div>
                <div class="recipe-item-container row">
                    <div class="recipe-item-pic">
                        <img src="{{object.pic.url}}" alt="" />
                    </div>
                    <div class="recipe-item-details">
                        <div class="recipe-item-stats row">
                            <div class="item-stats">
                                <p>
                                    <span
                                        class="material-symbols-outlined icon"
                                    >
                                        schedule
                                    </span>
                                    {{object.cooking_time}} Minutes
                                </p>
                            </div>

                            <div class="item-stats">
                                <p>
                                    <span
                                        class="material-symbols-outlined icon"
                                    >
                                        speed
                                    </span>
                                    Difficuly: {{object.calculate_difficulty}}
                                </p>
                            </div>
                        </div>
                        <div class="recipe-items">
                            <p>
                                <span class="bold">Description: </span
                                >{{object.description}}
                            </p>
                        </div>
                        <hr />
                        <div class="recipe-items">
                            <p>
                                <span class="bold">Ingredients: </span
                                >{{object.ingredients}}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

src/recipes/templates/recipes/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="{% static 'recipes/css/style.css' %}" />
        <!--google icons reference location to get directory-->
        <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />
        <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />
        <title>Recipe</title>
    </head>
    <body>
        <div class="recipes container">
            <div class="section-title">
                <h2>Simple and Tasty Recipes</h2>
                <p>Check out these great recipes</p>
            </div>

            <div class="recipe-cards">
                {% for object in object_list %}
                <a href="{{object.get_absolute_url}}" class="card">
                    <img id="pic" src="{{object.pic.url}}" alt="" />
                    <h5>{{object.name}}</h5>
                    <div class="flex-status row">
                        <div class="row">
                            <p>
                                <span class="material-symbols-outlined icon">
                                    schedule
                                </span>
                                {{object.cooking_time}} Minutes
                            </p>
                        </div>
                        <div class="row">
                            <p>
                                <span class="material-symbols-outlined icon">
                                    speed
                                </span>
                                Difficuly: {{object.calculate_difficulty}}
                            </p>
                        </div>
                    </div>
                    <div class="like row">
                        <i class="fa fa-heart" aria-hidden="true"></i>
                    </div>
                </a>
                {% endfor %}
            </div>
        </div>
    </body>
</html>

src/recipes/templates/recipes/recipes_home.html
<!--load all static files before creating HTML page-->
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="../../static/recipes/css/style.css" />
        <!--font awesome reference location to get directory-->
        <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
        <!--Icon Scout CDN-->

        <title>Welcome to the Recipe App</title>
    </head>
    <body>
        <div class="banner">
            <div class="navbar">
                <img src="{% static 'recipes/images/logo.png' %}" alt="logo" />
                <nav class="navigation row">
                    <ul class="primary-links row">
                        <li><a href="{% url 'recipes:home' %}">Home</a></li>
                        <li><a href="{% url 'recipes:list' %}">Recipes</a></li>
                        <li><a href="#">Create Recipe</a></li>
                        <li><a href="#">Contact</a></li>
                        <li><a href="{% url 'recipes:records' %}">Search</a></li>
                        <li>
                            {% if request.user.is_authenticated %}
                            <a href="{% url 'logout' %}">Logout</a>
                            {% else %}
                            <a href="{%url 'login' %}">Login</a>
                            {% endif %}
                        </li>
                    </ul>
                </nav>
                <ul class="secondary-links row">
                    <li>
                        <a
                            href="https://facebook.com"
                            target="_blank"
                            rel="”noreferrer”"
                            ><i
                                class="fa fa-facebook-official fa-lg"
                                aria-hidden="true"
                            ></i
                        ></a>
                    </li>
                    <li>
                        <a
                            href="https://instagram.com"
                            target="_blank"
                            rel="”noreferrer”"
                            ><i
                                class="fa fa-instagram fa-lg"
                                aria-hidden="true"
                            ></i
                        ></a>
                    </li>
                    <li>
                        <a
                            href="https://twitter.com"
                            target="_blank"
                            rel="”noreferrer”"
                            ><i
                                class="fa fa-twitter-square fa-lg"
                                aria-hidden="true"
                            ></i
                        ></a>
                    </li>
                </ul>
            </div>

            <!--End of Navigation-->

            <!--Main Content Section-->
            <section class="main">
                <div class="container row">
                    <div class="main-content">
                        <div class="content">
                            <div class="recipe row">
                                <img
                                    src="{% static 'recipes/images/notebook.png' %}"
                                    alt="Menu"
                                />Hot Recipes
                            </div>

                            <h1>Spicy Delicious Chicken Wings?</h1>
                            <p id="recipe-detail">
                                Click the View Recipes button to find out more
                                about how great recipes are made
                            </p>
                            <div class="sub-containter row">
                                <div class="time row">
                                    <svg
                                        xmlns="http://www.w3.org/2000/svg"
                                        width="24"
                                        height="24"
                                        viewBox="0 0 24 24"
                                        style="fill: rgba(255, 255, 255, 1)"
                                    >
                                        <path
                                            d="M12 2C6.486 2 2 6.486 2 12s4.486 10 10 10 10-4.486 10-10S17.514 2 12 2zm0 18c-4.411 0-8-3.589-8-8s3.589-8 8-8 8 3.589 8 8-3.589 8-8 8z"
                                        ></path>
                                        <path
                                            d="M13 7h-2v5.414l3.293 3.293 1.414-1.414L13 11.586z"
                                        ></path>
                                    </svg>
                                    <p>30 minutes</p>
                                </div>
                                <div class="time row">
                                    <svg
                                        xmlns="http://www.w3.org/2000/svg"
                                        width="24"
                                        height="24"
                                        viewBox="0 0 24 24"
                                        style="fill: rgba(255, 255, 255, 1)"
                                    >
                                        <path
                                            d="M21 10H3a1 1 0 0 0-1 1 10 10 0 0 0 5 8.66V21a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-1.34A10 10 0 0 0 22 11a1 1 0 0 0-1-1zM9 9V7.93a4.51 4.51 0 0 0-1.28-3.15A2.49 2.49 0 0 1 7 3V2H5v1a4.51 4.51 0 0 0 1.28 3.17A2.49 2.49 0 0 1 7 7.93V9zm4 0V7.93a4.51 4.51 0 0 0-1.28-3.15A2.49 2.49 0 0 1 11 3V2H9v1a4.51 4.51 0 0 0 1.28 3.15A2.49 2.49 0 0 1 11 7.93V9zm4 0V7.93a4.51 4.51 0 0 0-1.28-3.15A2.49 2.49 0 0 1 15 3V2h-2v1a4.51 4.51 0 0 0 1.28 3.15A2.49 2.49 0 0 1 15 7.93V9z"
                                        ></path>
                                    </svg>
                                    <p>Chicken</p>
                                </div>
                            </div>

                            <div class="main-btn row">
                                <a href="{% url 'recipes:list' %}"
                                    >View Recipes
                                    <i class="fa fa-play" aria-hidden="true"></i
                                ></a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </body>
</html>

src/recipes/templates/recipes/records.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="{% static 'recipes/css/style.css' %}" />
        <!--google icons reference location to get directory-->
        <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />
        <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />

        <title>Recipe</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <style>
            .recipe-detail-container {
                width: 100%;
                height: 100vh;
                background-color: #fff;
            }

            .recipe-detail-banner {
                width: 100%;
                height: 50vh;
                background-image: linear-gradient(
                        rgba(149, 21, 10, 0.75),
                        rgba(149, 21, 10, 0.75)
                    ),
                    url(../../static/recipes/images/recipe_list_page_pic.jpg);
                background-size: cover;
                background-position: center;
            }

            .recipe-header-container {
                width: 100%;
                margin: auto;
                padding: 5% 0 2% 0;
                display: flex;
                justify-content: space-between;
                align-items: center;
            }

            .recipe-header-container h2 {
                margin-left: 5px;
                font-weight: 600;
                font-size: 2em;
                color: #fff;
            }

            .flex-row {
                display: flex;
            }

            .recipe-detail-navbar {
                font-size: 1.3rem;
                
                margin-left: 10px;
                padding: 35px 0 10px 0;
                display: flex;
                align-items: center;
                justify-content: space-between;
            }

            .recipe-detail-navbar ul li {
                list-style: none;
                display: inline-block;
                margin: 0 10px;
            }

            .recipe-detail-navbar ul li a {
                list-style: none;
                text-decoration: none;
                color: #fff;
                
            }

            .records-form {
                font-size: 1.1rem;
                color: #fff;
                display: flex;
                justify-content: space-around;
                gap: 5px;
                margin-right: 20px;
                align-items: center;
            }

            .records-container {
                width: 90%;
                height: 300px;
                display: grid;
                grid-template-columns: repeat(2, 1fr);
                justify-items: center;

                gap: 5rem;
                margin: 35vh auto;
            }


            .search-btn {
                width: 120px;
                height: 2.375rem;
                font-weight: 600;
                font-size: 1rem;
                background: #fff;
                padding: 0.25em;
                
                
                border-radius: 5px;
                border: none;
              
            }

            .search-btn:hover {
                background: #683110;
                color: #fff;
            }

            .input-box {
                width: 200px;
                color: #495057;
                height: 2.375rem;
                padding: 0.375rem 0.75rem;
                border-radius: 0.25rem;
                border: 1px solid #000;
                background-clip: padding-box;
                transition: border-color 0.15s ease-in-out,
                    box-shadow 0.15s ease-in-out;
                margin-right: 1rem;
            }

            .chart-input {
                margin-right: 1.6rem;
            }

            .input-box::placeholder {
                padding: 1px;
                font-size: 1rem;
            }

            .ingredient-input:focus,
            .ingredient-input:active {
                border-color: #fff;
                background-color: transparent;
                color: #fff;
            }
        </style>
    </head>
    <body>
        <div class="recipe-detail-container">
            <div class="recipe-detail-banner">
                <div class="recipe-header-container">
                    <nav class="recipe-detail-navbar">
                        <ul class="flex-row">
                            <li>
                                <a href="{% url 'recipes:home' %}">Home</a>
                            </li>
                            <li>
                                <a href="{% url 'recipes:list' %}">Recipes</a>
                            </li>
                            <li><a href="#">Create Recipe</a></li>
                            <li><a href="{%url 'logout' %}">Logout</a></li>
                        </ul>
                    </nav>

                    <div class="records-form">
                        <form action="" method="POST">
                            {% csrf_token %} {{form}}
                            <button class="search-btn" type="submit">Search</button>
                        </form>
                    </div>
                </div>
                <div class="records-container">
                    <div>
                        {% if recipes_df %} {{recipes_df|safe}}
                    </div>
                    <div>
                        <img src="data:image/png;base64, {{chart|safe}}" />
                    </div>

                    
                    {% else %}
                    <h3>no data</h3>
                    {% endif %}
                </div>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>